### ISSUE TITLE
2.0.4 is broken

### ISSUE THREAD

**Issue by dashkan** [infinitycube/gravatar#10]
After upgrading to 2.0.4 the package.json file in the module no longer has main and typings entries which causes error TS2307: Cannot find module '@infinitycube/gravatar'.

Here is 2.0.4 package.json in node_modules/@infinitycube/gravatar
```javascript
{
  "_from": "@infinitycube/gravatar@^2.0.4",
  "_id": "@infinitycube/gravatar@2.0.4",
  "_inBundle": false,
  "_integrity": "sha512-uHeRZ9Q3kvte2AbL+5wnnd4v3/oA4c4Gl3ah9AWYNQq8bEME4JCPIUMIht6+yDwPRcmIDWeFf/v5RRSXjiAuEw==",
  "_location": "/@infinitycube/gravatar",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "@infinitycube/gravatar@^2.0.4",
    "name": "@infinitycube/gravatar",
    "escapedName": "@infinitycube%2fgravatar",
    "scope": "@infinitycube",
    "rawSpec": "^2.0.4",
    "saveSpec": null,
    "fetchSpec": "^2.0.4"
  },
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/@infinitycube/gravatar/-/gravatar-2.0.4.tgz",
  "_shasum": "fb449e921e84ba864c0155e0214ebebe0127a27a",
  "_spec": "@infinitycube/gravatar@^2.0.4",
  "_where": "/Users/ashkan/Projects/nbc/dali/src/UI/Dali.UI/Client",
  "author": {
    "name": "Gopakumar",
    "email": "me@gopumon.in"
  },
  "bugs": {
    "url": "https://github.com/infinitycube/gravatar/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "Gravatar directive for Angular 6 or later",
  "homepage": "https://github.com/infinitycube/gravatar#readme",
  "keywords": [
    "gravatar",
    "angular",
    "ngx",
    "directive"
  ],
  "license": "MIT",
  "name": "@infinitycube/gravatar",
  "peerDependencies": {
    "@angular/common": "^6.0.0 || ^7.0.0",
    "@angular/core": "^6.0.0 || ^7.0.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/infinitycube/gravatar.git"
  },
  "version": "2.0.4"
}
```

Vs 2.03
```javascript
{
  "_args": [
    [
      "@infinitycube/gravatar@2.0.3",
      "/Users/ashkan/Projects/nbc/dali/src/UI/Dali.UI/Client"
    ]
  ],
  "_from": "@infinitycube/gravatar@2.0.3",
  "_id": "@infinitycube/gravatar@2.0.3",
  "_inBundle": false,
  "_integrity": "sha512-jsIg6hoNwgZMbZZ855UDpRbtZ+/N6JWuDsxuo4ElkzYx2PNuBKaSNoljBH3Ey5OLplYrRQR7tEFoxhY6H9lWIg==",
  "_location": "/@infinitycube/gravatar",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "@infinitycube/gravatar@2.0.3",
    "name": "@infinitycube/gravatar",
    "escapedName": "@infinitycube%2fgravatar",
    "scope": "@infinitycube",
    "rawSpec": "2.0.3",
    "saveSpec": null,
    "fetchSpec": "2.0.3"
  },
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/@infinitycube/gravatar/-/gravatar-2.0.3.tgz",
  "_spec": "2.0.3",
  "_where": "/Users/ashkan/Projects/nbc/dali/src/UI/Dali.UI/Client",
  "author": {
    "name": "Gopakumar",
    "email": "me@gopumon.in"
  },
  "bugs": {
    "url": "https://github.com/infinitycube/gravatar/issues"
  },
  "dependencies": {
    "tslib": "^1.9.0"
  },
  "description": "Gravatar directive for Angular 6 or later",
  "es2015": "fesm2015/infinitycube-gravatar.js",
  "esm2015": "esm2015/infinitycube-gravatar.js",
  "esm5": "esm5/infinitycube-gravatar.js",
  "fesm2015": "fesm2015/infinitycube-gravatar.js",
  "fesm5": "fesm5/infinitycube-gravatar.js",
  "homepage": "https://github.com/infinitycube/gravatar#readme",
  "keywords": [
    "gravatar",
    "angular",
    "ngx",
    "directive"
  ],
  "license": "MIT",
  "main": "bundles/infinitycube-gravatar.umd.js",
  "metadata": "infinitycube-gravatar.metadata.json",
  "module": "fesm5/infinitycube-gravatar.js",
  "name": "@infinitycube/gravatar",
  "peerDependencies": {
    "@angular/common": "^6.0.0-rc.0 || ^6.0.0",
    "@angular/core": "^6.0.0-rc.0 || ^6.0.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/infinitycube/gravatar.git"
  },
  "sideEffects": false,
  "typings": "infinitycube-gravatar.d.ts",
  "version": "2.0.3"
}
```

**Comment by gopumon** [comment]
Thank you @dashkan for the bug report. I accidentally published the wrong. Kindly update to 2.0.5 to resolve the issue.
